/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chiptool;

/**
 *
 * @author jnu
 */
public class Toolswindow extends javax.swing.JFrame {

    char[] gdata = null;
    int[] chipdata = null;
    int[] anndata = null;

    /**
     * Creates new form Toolswindow
     */

    public Toolswindow(String Cfname, String Gfname, String Afname, char[] g, int[] chip, int[] ann) {
        initComponents();
        //create information to display
        String info = "Genome file: " + Gfname + "\n" + "ChipSeq file: " + Cfname + "\n" + "Annotation file: " + Afname;
        jTextAreainfo.setText(info);
        gdata = g;
        chipdata = chip;
        anndata = ann;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreainfo = new javax.swing.JTextArea();
        jButtoncallbrowser = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemchipdistance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreainfo.setColumns(20);
        jTextAreainfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreainfo);

        jButtoncallbrowser.setText("Show Browser");
        jButtoncallbrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncallbrowserActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Plots");

        jMenuItemchipdistance.setText("Chip Seq distance distribution");
        jMenuItemchipdistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemchipdistanceActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemchipdistance);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButtoncallbrowser)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtoncallbrowser)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncallbrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncallbrowserActionPerformed
        // TODO add your handling code here:
        Browser newob = new Browser(gdata, anndata, chipdata);
        
        //Caller ob= new Caller(gdata, chipdata,anndata);
        //ob.start();
    }//GEN-LAST:event_jButtoncallbrowserActionPerformed

    private void jMenuItemchipdistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemchipdistanceActionPerformed
        // TODO add your handling code here:
        Plotdistribution ob = new Plotdistribution(chipdata);
        //ob.plotdistance();
        ob.start();
        Histogramplots ob2=new Histogramplots();
        ob2.doplot();
    }//GEN-LAST:event_jMenuItemchipdistanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toolswindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toolswindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toolswindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toolswindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Toolswindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncallbrowser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemchipdistance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreainfo;
    // End of variables declaration//GEN-END:variables
}
